### ISSUE TITLE
Expanded hyperlinks

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#16]
Would it be possible (based on the GND links of person entries) to automatically incorporate links to ACDH-CH projects such as ÖML and ÖBL? It works with Wikidata links, so I assume this would also be possible with these projects?

**Comment by linxOD** [comment]
ÖML: https://www.wikidata.org/wiki/Property:P8432
ÖBL: https://www.wikidata.org/wiki/Property:P6194

**Comment by linxOD** [comment]
oebl and oeml URIs are now part of the person detail pages e.g. https://hanslick-online.github.io/hsl-app-dev/hsl_person_id_2416.html

No all persons have these Identifies. YOu can find them in Baserow.
