### ISSUE TITLE
[Possible] distinction between fictional and historic persons

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#17]
Let us discuss whether a distinction between fictional and historic persons in the actual texts (by using a different color) is advisable. The label already exists, so it should be possible without great efforts, but let's speak about the issue in person.

**Comment by AlexanderWilfing** [comment]
Another thought: it might be more difficult to do this in the texts itself (as the color is based on the "person" attribute in Oxygen, I assume), but we could do it quite easily in the index, right? Anyway, this is something that we should actually discuss in person next month.

**Comment by linxOD** [comment]
check back element id before creating rs type

**Comment by AlexanderWilfing** [comment]
Great solve, thanks! Could we use a different color, though? The current one is quite close to the yellow used for places. Maybe green?

**Comment by AlexanderWilfing** [comment]
I like the solution, especially the new way of visualizing annotations. A final minor issue is the placement of upper-case numbers if there is more than one annotations reference, for example in line 2 here: https://hanslick-online.github.io/hsl-app-dev/c__1903.11.27.html?wrk=on.
