### ISSUE TITLE
Annotations and Column / Page Breaks

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#48]
The change in the display of annotations (symbols instead of highlighting) has generated a problem. If parts of an annotated entity are in two different columns / pages, we used to actually include two annotations to create a continuous highlighting, e.g.

   ... Ist das nicht <rs type="person" ref="#hsl_person_id_319">wagne</rs></p>
   <pb facs="#facs_3" n="3" xml:id="img_0003"/>
   <cb n="7"/>
   <p prev="true">
   <lb facs="#facs_3_region_1684822668181_628_tl_1" n="N001" break="no"/><rs type="person" ref="#hsl_person_id_319">r</rs>isch, 

With the change to icons, these double annotations are superfluous and look rather silly (see https://hanslick-online.github.io/hsl-app-dev/c__1894.05.30.html?pbs=on&prs=on#__p18__lb229). If I am not mistaken, we can find these cases easily by searching for n="N001" break="no"/><rs type=, correct? If so, I can change these cases (there are only twenty) manually and only add the reference preceding the page break. Or is there a better solution in terms of data correctness?

**Comment by linxOD** [comment]
as quick fix that works with the TEI schema is the "prev" attribute. The same as for paragraphs (p).
If you encounter such a workbreak divided by columns, paragraph or page please add `prev="true"` to following `rs` element. However, keep all the other attributes like type, and ref.

**Comment by AlexanderWilfing** [comment]
Much better, but not perfect. The second icon does not show anymore, but the "r", which in in the continued annotation, is also gone. See https://hanslick-online.github.io/hsl-app-dev/c__1894.05.30.html?pbs=on&prs=on#__p19__lb230 and the screenshot below. I hope the XML text is okay and I didn't commit an error on my end...
![Example](https://github.com/Hanslick-Online/hsl-app/assets/104765618/811bf99b-9387-42b0-b26d-b9816c568f1d)
