### ISSUE TITLE
Facsimile of newly found texts

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#53]
We need to include the facsimile of newly found texts available via ANNO and already integrated in our Zotero library.

**Comment by AlexanderWilfing** [comment]
The dates of newly found texts are: 1898.02.01., 1896.02.16., 1892.06.05., 1891.05.14., 1890.02.24, 1889.06.09., 1888.11.08., 1887.10.23, 1887.04.10., 1886.02.06., 1884.04.03., 1884.01.25., 1882.12.20., 1882.12.19., 1880.12.22., 1880.12.14., 1879.04.08. All are to be found in this collection: https://www.zotero.org/groups/4767255/hanslicks_criticism/collections/E8ML3K2Y

**Comment by linxOD** [comment]
https://github.com/Hanslick-Online/hsl-data-ct/commit/88d57003c3fb627892e030174d9cf7a20dfb2d88
