### ISSUE TITLE
YouTube Video

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#55]
Embedding of Hanslick Concert Video https://www.youtube.com/watch?v=zIbSLcYHQSg&t=1s in paratext "Veranstaltungen" in German and English.

**Comment by AlexanderWilfing** [comment]
Sorry, a small issue remaining: the link you embedded starts the video at 53:26. Could you replace it with a link that starts the video from the beginning? Again, in both the English and German version of "Veranstaltungen"? Thanks and no rush.

**Comment by linxOD** [comment]
For me it starts from the beginning. I think this has something to do with your cache or you are logged in into Youtube and it saved your state?

**Comment by AlexanderWilfing** [comment]
Perfect, I guess the mistake was mine. Cheers!
