### ISSUE TITLE
Intern

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#56]
Please create the option of including last spring's intern, Sophie Rolandi, in the header of TEI files (just as in the cases of Mercedes de Luis Andres, Cornelia Pijec, and Annika Thell). Her ORCID is https://orcid.org/0009-0004-7945-8264. No rush, the end of June is early enough.

**Comment by linxOD** [comment]
Please also add her as "Projektmitarbeiterin" in all the documents she worked with:

```XML
        <editionStmt>
            <edition>Hanslick Edition: Hanslick in Neue Freie Presse</edition>
            <respStmt>
               <resp>Herausgegeben von</resp>
               <name ref="https://orcid.org/0000-0002-0117-3574">Wilfing, Alexander</name>
            </respStmt>
            <respStmt>
               <resp>Projektmitarbeiterinnen</resp>
               <name ref="https://orcid.org/0009-0006-9062-5902">Bamer, Katharina</name>
               <name ref="https://orcid.org/0000-0002-7722-4091">Pfiel, Anna-Maria</name>
               <name ref="https://orcid.org/0000-0002-0636-4476">Elsner, Daniel</name>
            </respStmt>
         </editionStmt>
 ```

**Comment by AlexanderWilfing** [comment]
Done, thanks!

**Comment by AlexanderWilfing** [comment]
Please create the option of including last spring's intern, Hanna Bertel, in the header of TEI files (just as in the cases of Mercedes de Luis Andres, Cornelia Pijec, Sophie Rolandi, and Annika Thell). Her ORCID is https://orcid.org/0009-0008-0705-1798. No rush, the texts she edited will only be released in December (probably). I already added her to the header.
