### ISSUE TITLE
Incorporate New Baserow Columns "Digitalisat"

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#58]
Please add the three newly created columns "Digitalisat", "Digitalisat 2," and "Digitalisat 3" in the "Werke" sheet of our Baserow database into the detailed view of works, both in the detailed view as part of the texts themselves (the pop-up windows) and in the detail view page of entities. This new field should only show if there is a link to a digital copy, i.e. if it is filled. (Do you know a better way of integrating more than 1 hyperlink than by creating multiple columns?) For now, I will be focusing on digital copies of text, but I might add digital copies of scores in the future (IMSLP).

**Comment by linxOD** [comment]
the easiest solution to avoid three or more columns is to switch to a regular "text field" and add multiples URLs with a seperator ",". E.g. <url>,<url>,<rul>

Another more complex solution would be to add a seperate table with multiple columns for URLs and connect the two tables.
However, the first solution would be enough. I can split the urls for the TEI/XML Index.

**Comment by AlexanderWilfing** [comment]
Perfect, will do that (solution 1). I guess a semicolon would work as a clear separator? And should there be a blank space before and after the separator or it this something that does not matter (e.g. "url; url" or "url ; url")? Just to make things as easy as possible on your end...

**Comment by linxOD** [comment]
the seperator should be something that does not exist in an url. I think a semicolon could be part of it. Maybe even a comma. The most save solution would be " , ". A comma with a leading and trailing whitespace.

**Comment by AlexanderWilfing** [comment]
Will do!

**Comment by linxOD** [comment]
done e.g. https://hanslick-online.github.io/hsl-app-dev/hsl_work_id_337.html

**Comment by AlexanderWilfing** [comment]
Please incorporate the link(s) to digital copies into the detailed view of works (e.g. https://hanslick-online.github.io/hsl-app-dev/hsl_work_id_200.html). Link(s) should be placed where the place holder "Digitalisat" is currently located, i.e. between GND number and "Erwähnt in". As discussed, I separated multiple links by blank spaces before and after a comma, i.e. " , "
