### ISSUE TITLE
Stadt-Wien project

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#60]
Please start working on the upcoming Stadt Wien project ("Der Kritiker in der Kritik: Die Rezensionen zu Eduard Hanslicks Traktat „Vom Musikalisch-Schönen“ (1854–1857)"). You should have access to the corresponding Zotero group library and Transkribus collection. What we require in the first place is a separate repository to work on these new texts (as of October 1, 2024) as well as an amended export from Transkribus (especially regarding the TEI header, as we will edit texts from various journals and newspapers and will have to fill in this information ourselves). Also, please keep in mind that users should have the option of including and excluding this new corpus into / from their search queries (just as they can currently decide whether to search VMS, the reviews, or both). Please get back to me with any questions!

**Comment by linxOD** [comment]
b3ab49f108e638d79b322e84320e2f598289056e
