### ISSUE TITLE
Index of Works (minor change)

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#62]
Please push the column giving the GND ID as much to the right as possible and use the created space in the table for the column "Titel". Btw, the released app and the dev app differ in this regard, so maybe you already addressed this issue? (If so, please just label the present "issue" as handled):

released: https://hanslick.acdh.oeaw.ac.at/listbibl.html

dev: https://hanslick-online.github.io/hsl-app-dev/listbibl.html

**Comment by linxOD** [comment]
The issue of the GND column having to much width is the entry: hsl_work_id_3203. Instead of a GND you added an archive.org url. The length of this url determines the column width for all other entries. Please remove this URL and add GND's only. This will resolve this issue.
